/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the AnnotatedSQL library.
 */
package ${pkgName};

import android.database.Cursor;
import java.util.Date;
import ${tableCanonicalName};

public class ${cursorWrapperName} extends AbstractCursorWrapper {

    public ${cursorWrapperName}(Cursor cursor) {
        super(cursor);
    }

    <#list columnNameList as columnName>
    <#if columnName != "_ID">
    public ${getClassTypeForColumn(columnName)} get${convertInCamelCase(columnName)}() {
        <#switch getClassTypeForColumn(columnName)>
        <#case "Integer">
        return getIntegerOrNull(${tableClassName}.${getVariableForColumn(columnName)});
        <#break>
        <#case "int">
        return getInt(${tableClassName}.${getVariableForColumn(columnName)});
        <#break>
        <#case "Long">
        return getLongOrNull(${tableClassName}.${getVariableForColumn(columnName)});
        <#break>
        <#case "long">
        return getLong(${tableClassName}.${getVariableForColumn(columnName)});
        <#break>
        <#case "Float">
        return getFloatOrNull(${tableClassName}.${getVariableForColumn(columnName)});
        <#break>
        <#case "float">
        return getFloat(${tableClassName}.${getVariableForColumn(columnName)});
        <#break>
        <#case "double">
        return getDoubleOrNull(${tableClassName}.${getVariableForColumn(columnName)});
        <#break>
        <#case "Double">
        return getDouble(${tableClassName}.${getVariableForColumn(columnName)});
        <#break>
        <#case "Boolean">
        return getBooleanOrNull(${tableClassName}.${getVariableForColumn(columnName)});
        <#break>
        <#case "boolean">
        return getBoolean(${tableClassName}.${getVariableForColumn(columnName)});
        <#break>
        <#case "Date">
        return getDate(${tableClassName}.${getVariableForColumn(columnName)});
        <#break>
        <#case "byte[]">
        return getBlob(${tableClassName}.${getVariableForColumn(columnName)});
        <#break>
        <#case "String">
        <#default>
        return getString(${tableClassName}.${getVariableForColumn(columnName)});
        </#switch>
    }
    </#if>
    </#list>


}