/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the AnnotatedSQL library.
  */
 
package ${pkgName};

public interface ${className}2 {
	<#list views as view>

	public static interface ${view.viewClassName}2 {
		<#list view.tables as subTable>
		
		public static interface ${subTable.className} {
			<#list subTable.columns as c>
			String ${c.variableName} = "${c.alias}";
			</#list>
		} 
		</#list>
	} 
	</#list>
	<#list queries as q>
		<#if q.hasSubTables>
	public static interface ${q.viewClassName}2 {
			<#list q.tables as subTable>
			
		public static interface ${subTable.className} {
			<#list subTable.columns as c>
			String ${c.variableName} = "${c.alias}";
			</#list>
		} 
			</#list>
	}
		</#if> 
	</#list>
}